// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkuxvejynljkkhlyikks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrdXh2ZWp5bmxqa2tobHlpa2tzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTYxMDcsImV4cCI6MjA3Mzc5MjEwN30.Xvsx04C9JJ4BFnpzBVDy9eqxm5fHmHbJZ51oMv8sDao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});